### PR TITLE
Version 1.0 BETA

### PR DESCRIPTION
**Pull request by Victorb101**
Created Version 1.0 board, schematic, bom, and gerbers. Only thing missing for BETA is MCAD.

### CODE REVIEW

**Comment by Victorb101** [comment]
@aaronbeekay Review for BETA

**Comment by aaronbeekay** [comment]
@Victorb101 - notes:

* It wouldn't have blocked approval of v1.0, but issue #3 is probably important to address.
* You've approved an Overlap error that shorts a signal to a solder nail on a connector:

image

This might be OK electrically but it isn't expected. It looks like that via could be moved just to the right of that pad to take care of the issue.

* Need board PDFs
* For some reason the .sch and .brd are in a folder with the Gerbers? Did you mean to do that?
* Your schematic says v1.3, but this will be v1.0.

**Comment by aaronbeekay** [comment]
I've gone ahead and merged this into Front-MCN-Breakout/v1.0 . This is how I'm planning on doing this in the future (more details soon).

@Victorb101, you are welcome to make commits against the v1.0 branch or this one, as you prefer.

**Comment by Victorb101** [comment]
@aaronbeekay This is ready to be pulled for Version 1.0

**Comment by aaronbeekay** [comment]
@Victorb101 - sorry this took so long. Design review feedback:

* Text on your silkscreen layers is in "Proportional" font - should be in "Vector"
* BOM format is incorrect.
* There are two copies of the design files (.brd and .sch) in the repo -- can you delete one?

**Comment by Victorb101** [comment]
@aaronbeekay Good to go

**Pull request merged**
